name: "Aptos Move Test for Compiler V2"
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'aptos-move/e2e-move-tests/**'
      - 'aptos-move/framework/**'
      - 'third_party/move/**'
      - '.github/workflows/move-test-compiler-v2.yaml'
      - '.github/actions/move-tests-compiler-v2/**'
  pull_request:
    types: [labeled, opened, synchronize, reopened, auto_merge_enabled]

env:
  CARGO_INCREMENTAL: "0"
  CARGO_TERM_COLOR: always

# cancel redundant builds
concurrency:
  # cancel redundant builds on PRs (only on PR, not on branches)
  group: ${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.ref) || github.sha }}
  cancel-in-progress: true

jobs:
  # Run Aptos Move Compiler v2 tests. This is a PR required job.
  rust-move-tests:
    runs-on: runs-on,cpu=64,family=c7,hdd=500,image=aptos-ubuntu-x64,run-id=${{ github.run_id }}
    steps:
      - uses: actions/checkout@v4
      - name: Run Aptos Move tests with compiler V2
        uses: ./.github/actions/move-tests-compiler-v2
        with:
          GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
