name: "*run execution-performance reusable workflow"

on:
  # This allows the workflow to be triggered from another workflow
  workflow_call:
    inputs:
      GIT_SHA:
        required: true
        type: string
        description: The git SHA1 to test.
      RUNNER_NAME:
        required: false
        default: executor-benchmark-runner 
        type: string
      IS_FULL_RUN:
        required: false
        default: false
        type: boolean
        description: Run complete version of the tests
      IGNORE_TARGET_DETERMINATION:
        required: false
        default: false
        type: boolean
        description: Ignore target determination and run the tests
  # This allows the workflow to be triggered manually from the Github UI or CLI
  # NOTE: because the "number" type is not supported, we default to 720 minute timeout
  workflow_dispatch:
    inputs:
      GIT_SHA:
        required: true
        type: string
        description: The git SHA1 to test.
      RUNNER_NAME:
        required: false
        default: executor-benchmark-runner 
        type: choice
        options:
        - executor-benchmark-runner
        description: The name of the runner to use for the test.
      IS_FULL_RUN:
        required: false
        default: false
        type: boolean
        description: Run complete version of the tests
      IGNORE_TARGET_DETERMINATION:
        required: false
        default: false
        type: boolean
        description: Ignore target determination and run the tests

jobs:
  # This job determines which tests to run
  test-target-determinator:
    runs-on: ubuntu-latest
    outputs:
      run_execution_performance_test: ${{ steps.determine_test_targets.outputs.run_execution_performance_test }}
    steps:
      - uses: actions/checkout@v4
      - name: Run the test target determinator
        id: determine_test_targets
        uses: ./.github/actions/test-target-determinator

  # Run single node execution performance tests
  single-node-performance:
    needs: test-target-determinator
    timeout-minutes: 60
    runs-on: ${{ inputs.RUNNER_NAME }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.GIT_SHA }}
        if: ${{ inputs.IGNORE_TARGET_DETERMINATION || needs.test-target-determinator.outputs.run_execution_performance_test == 'true' }}

      - uses: aptos-labs/aptos-core/.github/actions/rust-setup@main
        with:
          GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
        if: ${{ inputs.IGNORE_TARGET_DETERMINATION || needs.test-target-determinator.outputs.run_execution_performance_test == 'true' }}

      - name: Run single node execution benchmark in performance build mode
        shell: bash
        run: TABULATE_INSTALL=lib-only pip install tabulate && testsuite/single_node_performance.py
        if: ${{ !inputs.IS_FULL_RUN && (inputs.IGNORE_TARGET_DETERMINATION || needs.test-target-determinator.outputs.run_execution_performance_test == 'true') }}

      - name: Run full version of the single node execution benchmark in performance build mode
        shell: bash
        run: TABULATE_INSTALL=lib-only pip install tabulate && FLOW=CONTINUOUS testsuite/single_node_performance.py
        if: ${{ inputs.IS_FULL_RUN && (inputs.IGNORE_TARGET_DETERMINATION || needs.test-target-determinator.outputs.run_execution_performance_test == 'true') }}

      - run: echo "Skipping single node execution performance! Unrelated changes detected."
        if: ${{ !inputs.IGNORE_TARGET_DETERMINATION && needs.test-target-determinator.outputs.run_execution_performance_test != 'true' }}
